export const QUERY_KEYS = {
  TABLE_DATA_KEY: "GET_TABLE_VIEW_DATA_LIST",
  TIMELINE_DATA_KEY: "GET_TIMELINE_VIEW_DATA_LIST",
  CALENDAR_DATA_KEY: "GET_CALENDAR_VIEW_DATA_LIST",
  VIEWS_DATA_KEY: "GET_VIEWS_LIST",
  TABLE_FIELDS_LIST: "GET_VIEWS_AND_FIELDS",
};
