export const mockColumns = Array.from({length: 5}, (_, index) => ({
  attributes: {
    field_permission: {
      edit_permission: true,
      field_id: "231442e6-4395-4232-910f-56419049340d",
      guid: "12f68b6d-5e1e-4399-82c0-ce8f3aa0bff1",
      label: "Name",
      role_id: "c06ce3e5-e8f0-4cb6-9afe-6456cd105334",
      table_slug: "time-line_test",
      view_permission: true,
    },
    format: "SINGLE_LINE",
    formula: "undefined + undefined",
    label: "",
    label_undefined: "   ",
    math: {
      label: "plus",
      value: "+",
    },
    options: [],
  },
  autofill_field: "",
  autofill_table: "",
  automatic: false,
  column: 0,
  default: "",
  enable_multilanguage: false,
  id: index,
  index: "string",
  is_editable: false,
  is_search: true,
  is_visible: false,
  is_visible_layout: false,
  label: "Loading...",
  order: 0,
  path_slug: "",
  relation_data: {
    auto_filters: null,
    cascading_tree_field_slug: "",
    cascading_tree_table_slug: "",
    commit_id: "",
    editable: false,
    field_from: "",
    field_to: "",
    id: "",
    is_system: false,
    is_user_id_default: false,
    object_id_from_jwt: false,
    relation_buttons: false,
    relation_field_slug: "",
    table_from: "",
    table_to: "",
    type: "",
    view_fields: null,
  },
  relation_id: "",
  relation_type: "",
  required: false,
  show_label: false,
  slug: "name",
  table_id: "ef3d73fa-c486-4ac2-a5a0-f32671ba80a7",
  table_slug: "",
  type: "SINGLE_LINE",
  unique: false,
  view_fields: null,
}));
