import {
  Dashboard,
  MenuBook,
  Settings,
  People,
  Person,
  Restaurant,
  DirectionsCar,
  LocalGroceryStore,
  GpsFixedOutlined,
  DashboardCustomize,
} from "@material-ui/icons";
import AnalyticsIcon from '@mui/icons-material/Analytics';
import PendingActionsIcon from '@mui/icons-material/PendingActions';
import PersonAddAltIcon from '@mui/icons-material/PersonAddAlt';
import GroupIcon from '@mui/icons-material/Group';
import InsertDriveFileIcon from "@material-ui/icons/InsertDriveFile";

export const menu = [
  {
    id: "dashboard",
    title: "dashboard",
    path: "/home/dashboard",
    isActive: false,
    icon: AnalyticsIcon,
    permission: "dashboard",
  },
  {
    id: "orders",
    title: "orders",
    path: "/home/orders",
    isActive: false,
    icon: PendingActionsIcon,
    permission: "orders",
  },
  {
    id: "patients",
    title: "patients",
    path: "/home/patients",
    isActive: false,
    icon: PersonAddAltIcon,
    permission: "patients",
  },
  {
    id: "staffs",
    title: "staffs",
    path: "/home/staffs",
    isActive: false,
    icon: GroupIcon,
    permission: "staffs"
  },
  {
    id: "catalog",
    title: "catalog",
    path: "/home/catalog",
    redirect: "/home/catalog/goods",
    isActive: true,
    icon: Restaurant,
    // children: [
    //   {
    //     id: "goods.settings",
    //     title: "goods",
    //     path: "/home/catalog/goods",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "category.settings",
    //     title: "category",
    //     path: "/home/catalog/category",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "attributes.settings",
    //     title: "attributes",
    //     path: "/home/catalog/attributes",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "brands.settings",
    //     title: "brands",
    //     path: "/home/catalog/brands",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "units.settings",
    //     title: "unit",
    //     path: "/home/catalog/units",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "tags.settings",
    //     title: "tags",
    //     path: "/home/catalog/tags",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "product_variants.settings",
    //     title: "product_variants",
    //     path: "/home/catalog/product_variants",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "combo.settings",
    //     title: "combo",
    //     path: "/home/catalog/combo",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "price_changers.settings",
    //     title: "price_changers",
    //     path: "/home/catalog/price-changers",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    //   {
    //     id: "rates.settings",
    //     title: "rates",
    //     path: "/home/catalog/rates",
    //     isChild: true,
    //     isActive: false,
    //     permission: "settings",
    //   },
    // ],
  },
  {
    id: "marketing",
    title: "marketing",
    path: "/home/marketing/stocks",
    redirect: "/home/marketing/stocks",
    isActive: true,
    icon: GpsFixedOutlined,
    children: [
      {
        id: "stock",
        title: "stock",
        path: "/home/marketing/stocks",
        isChild: true,
        isActive: false,
        permission: "marketing",
      },
    ],
  },
  {
    id: "courier",
    title: "courier",
    path: "/home/courier",
    isActive: true,
    icon: DirectionsCar,
    permission: "courier",
    redirect: "/home/courier/list",
    children: [
      {
        id: "courier_child",
        title: "courier",
        path: "/home/courier/list",
        isActive: false,
        permission: "courier",
        isChild: true,
      },
      {
        id: "courier_type",
        title: "courier.type",
        path: "/home/courier/courier-type",
        isActive: false,
        permission: "courier_type",
        isChild: true,
      },
    ],
  },
  /* *** READY BUT MAY MALFUNCTION *** */
  // {
  //   id: "reports",
  //   title: "reports",
  //   path: "/home/reports",
  //   isActive: true,
  //   icon: InsertDriveFileIcon,
  //   permission: "reports",
  //   redirect: "/home/reports/courier",
  //   children: [
  //     {
  //       id: "courier_child",
  //       title: "courier",
  //       path: "/home/reports/courier",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "restaurants",
  //       path: "/home/reports/restaurants",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "users",
  //       path: "/home/reports/users",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "cities",
  //       path: "/home/reports/cities",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //   ],
  // },
  // {
  //   id: "catalog",
  //   title: "catalog",
  //   path: "/home/catalog",
  //   isActive: true,
  //   redirect: "/home/catalog/news",
  //   icon: MenuBook,
  //   children: [
  //     {
  //       id: "news",
  //       title: "news",
  //       path: "/home/catalog/news",
  //       isActive: false,
  //       permission: "news",
  //       isChild: true,
  //     },
  //     {
  //       id: "company_category",
  //       title: "company_category",
  //       path: "/home/catalog/company_category",
  //       isActive: false,
  //       permission: "company_category",
  //       isChild: true,
  //     },
  //     {
  //       id: "banner",
  //       title: "banner",
  //       path: "/home/catalog/banner",
  //       isActive: false,
  //       permission: "banner",
  //       isChild: true,
  //     },
  //   ],
  // },
  {
    id: "settings",
    title: "settings",
    path: "/home/settings",
    isActive: true,
    icon: Settings,
    redirect: "/home/settings/branch",
    children: [
      {
        id: "branch",
        title: "branch",
        path: "/home/settings/branch",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "documents",
        title: "documents",
        path: "/home/settings/documents",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "templates",
        title: "templates",
        path: "/home/settings/template",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "catalog",
        title: "catalog",
        path: "/home/settings/services/catalog",
        isActive: false,
        permission: "fares",
        isChild: true,
        children: [
          {
            id: "catalog",
            title: "catalog.list",
            path: "/home/settings/services/catalog",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
          {
            id: "category",
            title: "categories",
            path: "/home/settings/services/category",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
          {
            id: "service",
            title: "services",
            path: "/home/settings/services/service",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
        ],
      },
      {
        id: "nomenclature",
        title: "nomenclature",
        path: "/home/settings/user-roles",
        isActive: false,
        permission: "fares",
        isChild: true,
      },

      {
        id: "requisites",
        title: "requisites",
        path: "/home/settings/requisites",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
    ],
  },

  // {
  //   id: 'new-offers',
  //   title: 'new.offers',
  //   path: '/home/new-offers',
  //   isActive: false,
  //   icon: Work,
  //   permission: 'new_offers'
  // },
  // {
  //   id: 'settings',
  //   title: 'settings',
  //   path: '/home/settings',
  //   isActive: true,
  //   icon: Settings,
  //   children: [
  //     {
  //       id: 'entity.types',
  //       title: 'entity.types',
  //       path: '/home/settings/entity-type',
  //       isChild: true,
  //       permission: 'entity_type'
  //     },
  //     {
  //       id: 'the.logic.of.the.discussion.of.applications',
  //       title: 'the.logic.of.the.discussion.of.applications',
  //       path: '/home/settings/diagram-list',
  //       isChild: true,
  //       permission: 'settings_permission_diagram'
  //     },
  //   ],
  // },
];

export const settings = [];

// export default menu
