import {
  Dashboard,
  MenuBook,
  Settings,
  People,
  Person,
  Restaurant,
  DirectionsCar,
  LocalGroceryStore,
  GpsFixedOutlined,
} from "@material-ui/icons";
import InsertDriveFileIcon from "@material-ui/icons/InsertDriveFile";

export const menu = [
  {
    id: "dashboard",
    title: "dashboard",
    path: "/home/dashboard",
    isActive: false,
    icon: Dashboard,
    permission: "dashboard",
  },
  {
    id: "orders",
    title: "orders",
    path: "/home/orders",
    isActive: false,
    icon: LocalGroceryStore,
    permission: "orders",
  },
  {
    id: "personal",
    title: "clients",
    path: "/home/personal/clients",
    isActive: true,
    icon: People,
  },
  {
    id: "person",
    title: "operator",
    path: "/home/operator",
    isActive: true,
    icon: Person,
    // children: [
    //   {
    //     id: "users",
    //     title: "company",
    //     path: "/home/operator",
    //     isActive: false,
    //     permission: "operator",
    //     isChild: true,
    //   },
    // ],
  },
  // {
  //   id: "company",
  //   title: "Список ресторанов",
  //   path: "/home/company/shipper-company",
  //   // redirect: '/home/settings/shipper-settings',
  //   isActive: true,
  //   icon: Restaurant,
  //   children: [
  //     // {
  //     //   id: 'company.settings',
  //     //   title: 'company.settings',
  //     //   path: '/home/settings/shipper-settings',
  //     //   isChild: true,
  //     //   permission: 'settings'
  //     // },
  //   ],
  // },
  {
    id: "catalog",
    title: "catalog",
    path: "/home/catalog",
    redirect: "/home/catalog/goods",
    isActive: true,
    icon: Restaurant,
    children: [
      {
        id: "goods.settings",
        title: "goods",
        path: "/home/catalog/goods",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
      {
        id: "category.settings",
        title: "category",
        path: "/home/catalog/category",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
      {
        id: "attributes.settings",
        title: "attributes",
        path: "/home/catalog/attributes",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
      {
        id: "brands.settings",
        title: "brands",
        path: "/home/catalog/brands",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
      {
        id: "units.settings",
        title: "unit",
        path: "/home/catalog/units",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
      {
        id: "tags.settings",
        title: "tags",
        path: "/home/catalog/tags",
        isChild: true,
        isActive: false,
        permission: "settings",
      },
    ],
  },
  {
    id: "marketing",
    title: "marketing",
    path: "/home/marketing/stocks",
    redirect: "/home/marketing/stocks",
    isActive: true,
    icon: GpsFixedOutlined,
    children: [
      {
        id: "stock",
        title: "stock",
        path: "/home/marketing/stocks",
        isChild: true,
        isActive: false,
        permission: "marketing",
      },
      // {
      //   id: "banners",
      //   title: "banners",
      //   path: "/home/marketing/banners",
      //   isChild: true,
      //   permission: "marketing",
      // },
      // {
      //   id: "reviews",
      //   title: "reviews",
      //   path: "/home/marketing/reviews",
      //   isChild: true,
      //   permission: "marketing",
      // },
      // {
      //   id: "newsletter",
      //   title: "newsletter",
      //   path: "/home/marketing/newsletter",
      //   isChild: true,
      //   permission: "marketing",
      // },
      // {
      //   id: "news",
      //   title: "company.collection",
      //   path: "/home/marketing/news",
      //   isActive: false,
      //   permission: "news",
      //   isChild: true,
      // },
    ],
  },
  {
    id: "courier",
    title: "courier",
    path: "/home/courier",
    isActive: true,
    icon: DirectionsCar,
    permission: "courier",
    redirect: "/home/courier/list",
    children: [
      {
        id: "courier_child",
        title: "courier",
        path: "/home/courier/list",
        isActive: false,
        permission: "courier",
        isChild: true,
      },
      {
        id: "courier_type",
        title: "courier.type",
        path: "/home/courier/courier-type",
        isActive: false,
        permission: "courier_type",
        isChild: true,
      },
    ],
  },
  // {
  //   id: "reports",
  //   title: "reports",
  //   path: "/home/reports",
  //   isActive: true,
  //   icon: InsertDriveFileIcon,
  //   permission: "reports",
  //   redirect: "/home/reports/courier",
  //   children: [
  //     {
  //       id: "courier_child",
  //       title: "courier",
  //       path: "/home/reports/courier",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "restaurants",
  //       path: "/home/reports/restaurants",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "users",
  //       path: "/home/reports/users",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //     {
  //       id: "courier_child",
  //       title: "cities",
  //       path: "/home/reports/cities",
  //       isActive: false,
  //       permission: "courier",
  //       isChild: true,
  //     },
  //   ],
  // },
  // {
  //   id: "catalog",
  //   title: "catalog",
  //   path: "/home/catalog",
  //   isActive: true,
  //   redirect: "/home/catalog/news",
  //   icon: MenuBook,
  //   children: [
  //     {
  //       id: "news",
  //       title: "news",
  //       path: "/home/catalog/news",
  //       isActive: false,
  //       permission: "news",
  //       isChild: true,
  //     },
  //     {
  //       id: "company_category",
  //       title: "company_category",
  //       path: "/home/catalog/company_category",
  //       isActive: false,
  //       permission: "company_category",
  //       isChild: true,
  //     },
  //     {
  //       id: "banner",
  //       title: "banner",
  //       path: "/home/catalog/banner",
  //       isActive: false,
  //       permission: "banner",
  //       isChild: true,
  //     },
  //   ],
  // },
  {
    id: "settings",
    title: "settings",
    path: "/home/settings",
    isActive: true,
    icon: Settings,
    redirect: "/home/settings/fares",
    children: [
      {
        id: "fares",
        title: "fares",
        path: "/home/settings/fares",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "integrations",
        title: "integrations",
        path: "/home/settings/integrations",
        isActive: false,
        permission: "fares",
        isChild: true,
        children: [
          {
            id: "payme",
            title: "payme",
            path: "/home/settings/integrations/payme",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
          {
            id: "Iiko",
            title: "Iiko",
            path: "/home/settings/integrations/iiko",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
          {
            id: "jowi",
            title: "jowi",
            path: "/home/settings/integrations/jowi",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
          {
            id: "click",
            title: "click",
            path: "/home/settings/integrations/click",
            isActive: false,
            permission: "fares",
            isChild: true,
          },
        ],
      },
      {
        id: "aggregator",
        title: "aggregator",
        path: "/home/settings/aggregator",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "user-roles",
        title: "user-roles",
        path: "/home/settings/user-roles",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
      {
        id: "company",
        title: "company",
        path: "/home/settings/company",
        isActive: false,
        permission: "fares",
        isChild: true,
      },
    ],
  },

  // {
  //   id: 'new-offers',
  //   title: 'new.offers',
  //   path: '/home/new-offers',
  //   isActive: false,
  //   icon: Work,
  //   permission: 'new_offers'
  // },
  // {
  //   id: 'settings',
  //   title: 'settings',
  //   path: '/home/settings',
  //   isActive: true,
  //   icon: Settings,
  //   children: [
  //     {
  //       id: 'entity.types',
  //       title: 'entity.types',
  //       path: '/home/settings/entity-type',
  //       isChild: true,
  //       permission: 'entity_type'
  //     },
  //     {
  //       id: 'the.logic.of.the.discussion.of.applications',
  //       title: 'the.logic.of.the.discussion.of.applications',
  //       path: '/home/settings/diagram-list',
  //       isChild: true,
  //       permission: 'settings_permission_diagram'
  //     },
  //   ],
  // },
];

export const settings = [];

// export default menu
